FROM maven:3.9-eclipse-temurin-21 AS build
WORKDIR /app
COPY . .
RUN mvn clean package -DskipTests

FROM eclipse-temurin:21-jre-alpine
WORKDIR /app
COPY --from=build /app/WebApi/target/web-api-1.0-SNAPSHOT.jar .
EXPOSE 8080
CMD ["java", "-jar", "web-api-1.0-SNAPSHOT.jar"]
